name: codeowners-validator-failures

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository, which is validated in the next step
      - uses: actions/checkout@v2
        with:
          ref: failures
      - name: GitHub CODEOWNERS Validator
        uses: mszostok/codeowners-validator@v0.7.1
        with:
          checks: "files,owners,duppatterns,syntax"
          experimental_checks: "notowned"

          # GitHub access token is required only if the `owners` check is enabled
          owner_checker_allow_unowned_patterns: "false"
          github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
